
#FROM python:3
#RUN git clone https://github.com/Carla-Sofia-Centeleghe/Practica_Final_Compu1.git
#WORKDIR /Practica_Final_Compu1.git
#RUN pip install -r requirements.txt
#CMD ["python3", "-m", "unittest"]